apiVersion: v1
kind: Service
metadata:
  name: my-internal-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: movies
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
